#!/bin/bash
signature="^"
trim="false"
command="ls"
optneeded="false"
while getopts s:toc: option
do
    case "${option}"
    in
        s) signature=${OPTARG};;
        t) trim="true";;
        o) optneeded="true";;
        c) command=${OPTARG};;
        *) ;;
    esac
done

if [ $optneeded == "false" ]
then
    command=""
    for var in "$@"
    do
        command="${command} ${var}"
    done
fi

py_exec="$( dirname "${BASH_SOURCE[0]}" )/main.py"
eval "$command" 2>&1 | python3 "$py_exec"
